### ISSUE TITLE
raw text

### ISSUE THREAD

**Issue by XiaoxinHe** [mm-graph-benchmark/mm-graph-benchmark#3]
Hi,

Thank you for introducing the Multimodal Graph Benchmark! I noticed that you provide instructions to download the raw images. I was wondering if you have any plans to open-source the raw text data as well. It would be a valuable addition to the resources. 

Thank you!

**Comment by jwzhi** [comment]
Thanks for contacting us. You can find the raw text here: https://cseweb.ucsd.edu/~jmcauley/datasets.html#amazon_reviews.

**Comment by jwzhi** [comment]
I can upload a script to get the raw text from metadata later. Please stay tuned for that. Thanks!

**Comment by jwzhi** [comment]
The raw data is here: https://huggingface.co/datasets/mm-graph-org/mm-graph/tree/main/raw-data
