### ISSUE TITLE
Raw Text of Node Labels and Corresponding Mappings

### ISSUE THREAD

**Issue by yf-he** [mm-graph-benchmark/mm-graph-benchmark#5]
Excellent work! It is greatly insightful and beneficial to the community. 

To further my understanding, I would be grateful if you could share the raw text of the node labels and their corresponding mappings for the Goodreads-NC and Ele-Fashion datasets?

Thank you very much for considering my request.

**Comment by jwzhi** [comment]
Thanks for the comments. You can find raw data here: https://huggingface.co/datasets/mm-graph-org/mm-graph/tree/main/raw-data
You can find mapping here in each corresponding data folder called 'node_mapping.pt', see an example here: https://huggingface.co/datasets/mm-graph-org/mm-graph/tree/main/ele-fashion
